product(bim_object, 1).
product(bim_object, 2).
product(bim_object, 3).
product(bim_object, 4).
product(bim_object, 5).
product(bim_object, 6).
product(bim_object, 7).
product(bim_object, 8).
product(bim_object, 9).
product(bim_object, 10).
product(bim_object, 11).
product(bim_object, 12).
product(bim_object, 13).
product(bim_object, 14).
product(bim_object, 15).
product(bim_object, 16).
product(bim_object, 17).
product(bim_object, 18).
product(bim_object, 19).
product(bim_object, 20).
product(bim_object, 21).
product(bim_object, 22).
product(bim_object, 23).
product(bim_object, 24).
product(bim_object, 25).
product(bim_object, 26).
product(bim_object, 27).
product(bim_object, 28).
product(bim_object, 29).
product(bim_object, 30).
product(bim_object, 31).
product(bim_object, 32).
product(bim_object, 33).
product(bim_object, 34).
product(bim_object, 35).
product(bim_object, 36).
product(bim_object, 37).
product(bim_object, 38).
product(bim_object, 39).
product(bim_object, 40).
product(bim_object, 41).
product(bim_object, 42).
product(bim_object, 43).
product(bim_object, 44).
product(bim_object, 45).
product(bim_object, 46).
product(bim_object, 47).
product(bim_object, 48).
product(bim_object, 49).
product(bim_object, 50).
product(bim_object, 51).
product(bim_object, 52).
product(bim_object, 53).
product(bim_object, 54).
product(bim_object, 55).
product(bim_object, 56).
product(bim_object, 57).
product(bim_object, 58).
product(bim_object, 59).
product(bim_object, 60).
product(bim_object, 61).
product(bim_object, 62).
product(bim_object, 63).
product(bim_object, 64).
product(bim_object, 65).
product(bim_object, 66).
product(bim_object, 67).
product(bim_object, 68).
product(bim_object, 69).
product(bim_object, 70).
product(bim_object, 71).
product(bim_object, 72).
product(bim_object, 73).
product(bim_object, 74).
product(bim_object, 75).
product(bim_object, 76).
product(bim_object, 77).
product(bim_object, 78).
product(bim_object, 79).
product(bim_object, 80).
product(bim_object, 81).
product(bim_object, 82).
product(bim_object, 83).
product(bim_object, 84).
product(bim_object, 85).
product(bim_object, 86).
product(bim_object, 87).
product(bim_object, 88).
product(bim_object, 89).
product(bim_object, 90).
product(bim_object, 91).
product(bim_object, 92).
product(bim_object, 93).
product(bim_object, 94).
product(bim_object, 95).
product(bim_object, 96).
product(bim_object, 97).
product(bim_object, 98).
product(bim_object, 99).
product(bim_object, 100).
product(bim_object, 101).
product(bim_object, 102).
product(bim_object, 103).
product(bim_object, 104).
product(bim_object, 105).
product(bim_object, 106).
product(bim_object, 107).
product(bim_object, 108).
product(bim_object, 109).
product(bim_object, 110).
product(bim_object, 111).
product(bim_object, 112).
product(bim_object, 113).
product(bim_object, 114).
product(bim_object, 115).
product(bim_object, 116).
product(bim_object, 117).
product(bim_object, 118).
product(bim_object, 119).
product(bim_object, 120).
product(bim_object, 121).
product(bim_object, 122).
product(bim_object, 123).
